using System;
using System.Collections.Generic;
using System.Text;

namespace MiExamenT1
{
    public class PokerGame
    {
        private Random rand = new Random();
        public List<Cartas> deck = new List<Cartas>();
        public PokerGame()
        {
            Cartas AofS = new Cartas(Palo.Espadas, Number.Ace);
            deck.Add(AofS);
            Cartas TwoofS = new Cartas(Palo.Espadas, Number.Dos);
            deck.Add(TwoofS);
            Cartas ThreeofS = new Cartas(Palo.Espadas, Number.Tres);
            deck.Add(ThreeofS);
            Cartas FourofS = new Cartas(Palo.Espadas, Number.Cuatro);
            deck.Add(FourofS);
            Cartas FiveofS = new Cartas(Palo.Espadas, Number.Cinco);
            deck.Add(FiveofS);
            Cartas SixofS = new Cartas(Palo.Espadas, Number.Seis);
            deck.Add(SixofS);
            Cartas SevenofS = new Cartas(Palo.Espadas, Number.Siete);
            deck.Add(SevenofS);
            Cartas EightofS = new Cartas(Palo.Espadas, Number.Ocho);
            deck.Add(EightofS);
            Cartas NineofS = new Cartas(Palo.Espadas, Number.Nueve);
            deck.Add(NineofS);
            Cartas TenofS = new Cartas(Palo.Espadas, Number.Diez);
            deck.Add(TenofS);
            Cartas JackofS = new Cartas(Palo.Espadas, Number.Jack);
            deck.Add(JackofS);
            Cartas QueenofS = new Cartas(Palo.Espadas, Number.Queen);
            deck.Add(QueenofS);
            Cartas KingofS = new Cartas(Palo.Espadas, Number.King);
            deck.Add(KingofS);
            Cartas AofH = new Cartas(Palo.Corazones, Number.Ace);
            deck.Add(AofH);
            Cartas TwoofH = new Cartas(Palo.Corazones, Number.Dos);
            deck.Add(TwoofH);
            Cartas ThreeofH = new Cartas(Palo.Corazones, Number.Tres);
            deck.Add(ThreeofH);
            Cartas FourofH = new Cartas(Palo.Corazones, Number.Cuatro);
            deck.Add(FourofH);
            Cartas FiveofH = new Cartas(Palo.Corazones, Number.Cinco);
            deck.Add(FiveofH);
            Cartas SixofH = new Cartas(Palo.Corazones, Number.Seis);
            deck.Add(SixofH);
            Cartas SevenofH = new Cartas(Palo.Corazones, Number.Siete);
            deck.Add(SevenofH);
            Cartas EightofH = new Cartas(Palo.Corazones, Number.Ocho);
            deck.Add(EightofH);
            Cartas NineofH = new Cartas(Palo.Corazones, Number.Nueve);
            deck.Add(NineofH);
            Cartas TenofH = new Cartas(Palo.Corazones, Number.Diez);
            deck.Add(TenofH);
            Cartas JackofH = new Cartas(Palo.Corazones, Number.Jack);
            deck.Add(JackofH);
            Cartas QueenofH = new Cartas(Palo.Corazones, Number.Queen);
            deck.Add(QueenofH);
            Cartas KingofH = new Cartas(Palo.Corazones, Number.King);
            deck.Add(KingofH);
            Cartas AofC = new Cartas(Palo.Trebol, Number.Ace);
            deck.Add(AofC);
            Cartas TwoofC = new Cartas(Palo.Trebol, Number.Dos);
            deck.Add(TwoofC);
            Cartas ThreeofC = new Cartas(Palo.Trebol, Number.Tres);
            deck.Add(ThreeofC);
            Cartas FourofC = new Cartas(Palo.Trebol, Number.Cuatro);
            deck.Add(FourofC);
            Cartas FiveofC = new Cartas(Palo.Trebol, Number.Cinco);
            deck.Add(FiveofC);
            Cartas SixofC = new Cartas(Palo.Trebol, Number.Seis);
            deck.Add(SixofC);
            Cartas SevenofC = new Cartas(Palo.Trebol, Number.Siete);
            deck.Add(SevenofC);
            Cartas EightofC = new Cartas(Palo.Trebol, Number.Ocho);
            deck.Add(EightofC);
            Cartas NineofC = new Cartas(Palo.Trebol, Number.Nueve);
            deck.Add(NineofC);
            Cartas TenofC = new Cartas(Palo.Trebol, Number.Diez);
            deck.Add(TenofC);
            Cartas JackofC = new Cartas(Palo.Trebol, Number.Jack);
            deck.Add(JackofC);
            Cartas QueenofC = new Cartas(Palo.Trebol, Number.Queen);
            deck.Add(QueenofC);
            Cartas KingofC = new Cartas(Palo.Trebol, Number.King);
            deck.Add(KingofC);
            Cartas AofD = new Cartas(Palo.Diamantes, Number.Ace);
            deck.Add(AofD);
            Cartas TwoofD = new Cartas(Palo.Diamantes, Number.Dos);
            deck.Add(TwoofD);
            Cartas ThreeofD = new Cartas(Palo.Diamantes, Number.Tres);
            deck.Add(ThreeofD);
            Cartas FourofD = new Cartas(Palo.Diamantes, Number.Cuatro);
            deck.Add(FourofD);
            Cartas FiveofD = new Cartas(Palo.Diamantes, Number.Cinco);
            deck.Add(FiveofD);
            Cartas SixofD = new Cartas(Palo.Diamantes, Number.Seis);
            deck.Add(SixofD);
            Cartas SevenofD = new Cartas(Palo.Diamantes, Number.Siete);
            deck.Add(SevenofD);
            Cartas EightofD = new Cartas(Palo.Diamantes, Number.Ocho);
            deck.Add(EightofD);
            Cartas NineofD = new Cartas(Palo.Diamantes, Number.Nueve);
            deck.Add(NineofD);
            Cartas TenofD = new Cartas(Palo.Diamantes, Number.Diez);
            deck.Add(TenofD);
            Cartas JackofD = new Cartas(Palo.Diamantes, Number.Jack);
            deck.Add(JackofD);
            Cartas QueenofD = new Cartas(Palo.Diamantes, Number.Queen);
            deck.Add(QueenofD);
            Cartas KingofD = new Cartas(Palo.Diamantes, Number.King);
            deck.Add(KingofD);
        }
}
